# where to put results
wdir: ""
# input
indir: "" # for multiple files after demultiplexing
infile: "" # one undemultiplexed file
gz: True

#SAMPLES
samples: ""
experiment_group_file: "" # txt file with group space sample per row
experiment_groups: ""
seq_format: "-Q33" # -Q33 for Illumnina -Q64 for Sanger needed by fastX

# barcodes
barcodeLength: 10 # if already demux = umi1_len
barcodeLength.read1: 0  # in paired end eCLIP data
minBaseQuality: 10
umi1_len: 10 # antisense of used barcodes --> this is the 3' umi of the original barcode
umi2_len: 0
exp_barcode_len: 0
encode_umi: False
encode_umi_length: "10" # is 5 for older encode eCLIPs


barcodes_fasta: "" # ! antisense of used barcodes, not needed if already demultiplexed
barcodes_fasta_R1: "" # only for paired end data
quality_filter_barcodes: True # if no demultiplexing is done, is there still a barcode

# demultiplexing
demuliplexing: False # Whether demultiplexing still has to be done, if FALSE exp_barcode_len should be 0, no bacode filtering will be done
flexbar_minReadLength: 15

#adapter adapter_trimming
adapter_file: "params.dir/adapter.fa"
adapter_file_R2: "params.dir/adapter.fa" # for paired en data adapter of read 2
adapter_cycles: 1
adapter_trimming: True

# star alignment
paired: False
gft: "" # has to be unzipped at the moment
genome_fasta: "" # has to be unzipped or bgzip
sjdbOverhang: 139 # readlength -1 - barcodelength - adapter much faster tospecify than to calculated from fastq file
outFilterMismatchNoverReadLmax: 0.04
outFilterMismatchNmax: 999
outFilterMultimapNmax: 1
alignEndsType: "Extend5pOfRead1"
outReadsUnmapped: "Fastx"
outSJfilterReads: "Unique"
moreSTARParameters: ""

# chimeric miR
miR: False
miR_genome_fasta: ""
miR_starts_allowed: "1 2 3 4"
