matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      ignores:
      - RBP
      - crosslinks
      - eCLIP
      - et
      - iCLIP
      - deduplication
      - demultiplexing
      - conda
      - al.
      - racoon_clip
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  sources:
  - '*.md'
  default_encoding: utf-8
