matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    encoding: utf-8
    dictionary:
    wordlists:
    - docs/src/dictionary/custom.txt
  pipeline:
  - pyspelling.filters.markdown:
      ignores:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  sources:
  - '*.md'
  default_encoding: utf-8
