# eCLIP ENCODE integration test without a transcript annotation
wdir: "./test/out_eCLIP_ENCODE_no_gtf"

infiles: "example_data/example_eCLIP_ENCODE/test_eCLIP_ENC_s1.chr21.fastq example_data/example_eCLIP_ENCODE/test_eCLIP_ENC_s2.chr21.fastq"

samples: "test_eCLIP_ENC_s1.chr21 test_eCLIP_ENC_s2.chr21"
experiment_group_file: "example_data/example_eCLIP_ENCODE/groups_test_eCLIP_ENC.txt"
experiment_groups: "test_eCLIP_ENC"

experiment_type: "eCLIP_ENCODE_5ntUMI"
quality_filter_barcodes: False

adapter_cycles: 2
adapter_trimming: True

genome_fasta: "example_data/example_annotation_human_chr21/test_annotation_chr21.fa"
gtf: ""
read_length: 45
