# where to put results
wdir: "/home/mek24iv/racoon_devel/racoon_clip/tests/test_dag/expected_output/out_iCLIP_multiplexed"

# input
infiles: "/home/mek24iv/racoon_devel/racoon_clip/example_data/example_iCLIP_multiplexed/test_iCLIP_multi.chr21.fastq.gz" # for multiple files after demultiplexing


#SAMPLES
samples: "test_iCLIP_s1.chr21 test_iCLIP_s2.chr21" # sample name needs to be identical for read 1 and 2 of same sample


experiment_type: "iCLIP2"
demultiplex: True
# if no demultiplexing is done, is there still a barcode
barcodes_fasta: "/home/mek24iv/racoon_devel/racoon_clip/example_data/example_iCLIP_multiplexed/barcodes.fa"

#adapter adapter_trimming
adapter_trimming: True
adapter_file: "/home/mek24iv/racoon_devel/racoon_clip/example_data/example_iCLIP_multiplexed/adapter.fa"

genome_fasta: "/home/mek24iv/racoon_devel/racoon_clip/example_data/example_annotation_human_chr21/test_annotation_chr21.fa" # has to be unzipped at the moment
gtf: "/home/mek24iv/racoon_devel/racoon_clip/example_data/example_annotation_human_chr21/test_annotation_chr21.gtf" # accepts fa and fa.gz
read_length: 45