# where to put results
wdir: "tests/test_config/expected_output/out_iCLIP"

# input
infiles: "example_data/example_iCLIP/test_iCLIP_s1.chr21.fastq example_data/example_iCLIP/test_iCLIP_s2.chr21.fastq" # for multiple files after demultiplexing


#SAMPLES
samples: "test_iCLIP_s1.chr21 test_iCLIP_s2.chr21" # sample name needs to be identical for read 1 and 2 of same sample


experiment_type: "iCLIP2"
demultiplex: "FALSE"
# if no demultiplexing is done, is there still a barcode
barcodes_fasta: "example_data/example_iCLIP/barcodes.fa"

#adapter adapter_trimming
adapter_trimming: True
adapter_file: "example_data/example_iCLIP/adapter.fa"

genome_fasta: "example_data/example_annotation_human_chr21/test_annotation_chr21.fa" # has to be unzipped at the moment
gtf: "example_data/example_annotation_human_chr21/test_annotation_chr21.gtf" # accepts fa and fa.gz
read_length: 45