adapter_cycles: 2
adapter_file: /racoon_clip-1.0.9/racoon_clip/workflow/params.dir/adapter.fa
adapter_trimming: 'True'
barcodeLength: 0
barcodes_fasta: ''
deduplicate: 'True'
demultiplex: 'False'
encode: 'False'
encode_umi_length: 10
experiment_group_file: ''
experiment_groups: ''
experiment_type: eCLIP_10ntUMI
experimental_barcode_len: 0
genome_fasta: <path/to/genome.fa>
gtf: <path/to/annotation.gtf>
infiles: <path/to/minimal_example/minimal_example_eCLIP/min_example_eCLIP_s1.fastq>
  <path/to/minimal_example/minimal_example_eCLIP/min_example_eCLIP_s2.fastq>
log: racoon_clip.log
minBaseQuality: 10
min_read_length: 15
moreSTARParameters: ''
outFilterMismatchNmax: 999
outFilterMismatchNoverReadLmax: 0.04
outFilterMultimapNmax: 1
outReadsUnmapped: Fastx
outSJfilterReads: Unique
quality_filter_barcodes: 'True'
read_length: 50
samples: min_example_eCLIP_s1_R2 min_example_eCLIP_s2_R2
seq_format: -Q33
snakebase: /racoon_clip-1.0.9/racoon_clip/workflow
umi1_len: 0
umi2_len: 0
wdir: <path/to/output/dir>
