# where to put results
wdir: "<path/to/output/dir>"
# input
infiles: "<path/to/minimal_example/minimal_example_iCLIP_multiplexed/min_example_iCLIP2_multiplexed.fastq.gz>"

experiment_type: "iCLIP2"

barcodes_fasta: "<path/to/minimal_example/minimal_example_iCLIP_multiplexed/barcodes.fasta>" # ! antisense of used barcodes, not needed if already demultiplexed


# demultiplexing
demultiplex: True 

#adapter adapter_trimming
adapter_file: "<path/to/minimal_example/minimal_example_iCLIP_multiplexed/adapter.fa>"

# star alignment
gtf: "<path/to/annotation.gtf>" # has to be unzipped at the moment
genome_fasta: "<path/to/genome.fa>" # has to be unzipped or bgzip
read_length: 150


experiment_groups: "min_example_iCLIP2_multiplexed_g1 min_example_iCLIP2_multiplexed_g2" # txt file with group space sample per row
experiment_group_file: "<path/to/minimal_example/groups.txt>"

samples: "min_example_iCLIP2_multiplexed_s1 min_example_iCLIP2_multiplexed_s2 min_example_iCLIP2_multiplexed_s3 min_example_iCLIP2_multiplexed_s4"