# where to put results
wdir: "<path/to/output/dir>"
# input
infiles: "<path/to/minimal_example/minimal_example_eCLIP/min_example_eCLIP_encode_s1.fastq>, "<path/to/minimal_example/minimal_example_eCLIP/min_example_eCLIP_encode_s2.fastq>" # for multiple files after demultiplexing
samples: "min_example_eCLIP_encode_s1 min_example_eCLIP_encode_s2"

# barcodes
experiment_type: "eCLIP_ENCODE_10ntUMI"
quality_filter_barcodes: False
adapter_cycles: 2

# star alignment
gtf: "<path/to/annotation.gtf>" # has to be unzipped at the moment
genome_fasta: "<path/to/genome.fa>" # has to be unzipped or bgzip
read_length: 45 
