name: Spellcheck Action

on: 
  push:
  workflow_dispatch:

jobs:
  build_markdown:
    name: Spellcheck Markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Spellcheck Markdown
        uses: rojopolis/spellcheck-github-actions@0.46.0
        with:
          source_files: README.md USER_MANUAL.md 
          task_name: Markdown
          output_file: markdown_spellcheck-output.txt
      - name: Upload Markdown Spellcheck Output
        uses: actions/upload-artifact@v4
        if: '!cancelled()' # Do not upload artifact if job was cancelled
        with:
          name: Markdown Spellcheck Output
          path: markdown_spellcheck-output.txt

  build_rst:
    name: Spellcheck reStructuredText
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Spellcheck reStructuredText
        uses: rojopolis/spellcheck-github-actions@0.46.0
        with:
          source_files: "docs/*.rst"
          task_name: reStructuredText
          output_file: rst_spellcheck-output.txt
      - name: Upload reStructuredText Spellcheck Output
        uses: actions/upload-artifact@v4
        if: '!cancelled()' # Do not upload artifact if job was cancelled
        with:
          name: reStructuredText Spellcheck Output
          path: rst_spellcheck-output.txt
