name: Docker Build and Push

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Get latest release version
        id: get_release_version
        run: echo "::set-output name=VERSION::${GITHUB_REF#refs/tags/}"
      
      - name: Update Dockerfile with new version
        run: sed -i "s/VERSION_PLACEHOLDER/${{ steps.get_release_version.outputs.VERSION }}/g" docker/Dockerfile
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: melinak
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag yourdockerusername/yourrepositoryname:latest \
            --tag yourdockerusername/yourrepositoryname:${{ steps.get_release_version.outputs.VERSION }} \
            .
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            --tag yourdockerusername/yourrepositoryname:latest \
            --tag yourdockerusername/yourrepositoryname:${{ steps.get_release_version.outputs.VERSION }} \
            .
        
