name: Docker Build and Push

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Specify the release version'
        required: true
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      # Check if workflow is triggered by workflow_dispatch
      - name: Check if manually triggered
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Manually triggered with release version: ${{ github.event.inputs.release_version }}"
          export RELEASE_VERSION="${{ github.event.inputs.release_version }}"
      
      # If not manually triggered, get git tag
      - name: Get git tag
        if: github.event_name != 'workflow_dispatch'
        id: tag
        uses: dawidd6/action-get-tag@v1
      
      - name: Update Dockerfile with new version
        run: sed -i "s#VERSION_PLACEHOLDER#${{ steps.tag.outputs.tag }}/g" docker/Dockerfile
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: melinak
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag melinak/racoon_clip:latest \
            --tag melinak/racoon_clip:${{ steps.tag.outputs.VERSION }} \
            .
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            --tag melinak/racoon_clip:latest \
            --tag melinak/racoon_clip:${{ steps.tag.outputs.VERSION }} \
            .
        
